services:
  spv_express:
    container_name: spv_express
    networks:
      - spotify_playlist_visualizer
    env_file: ".env"
    build:
      context: ../../
      dockerfile: ./src/backend/Dockerfile.express
    ports:
      - "9988:9988"
    depends_on:
      - spv_flask
      - postgres

  spv_flask:
    container_name: spv_flask
    networks:
      - spotify_playlist_visualizer
    environment:
      - FLASK_PORT=9989
    build:
      context: ./
      dockerfile: ./Dockerfile.flask

  postgres:
    container_name: spv_postgres
    networks:
      - spotify_playlist_visualizer
    image: postgres
    env_file: ".env" # Includes the POSTGRES_PASSWORD
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:

networks:
  spotify_playlist_visualizer:
    driver: bridge