# TO BE RUN FROM DOCKER COMPOSE. DO NOT RUN MANUALLY AS CONTEXT IS NOT SET CORRECTLY

FROM python:3.11

# Set the working directory
WORKDIR /app

# Copy the requirements file and install the dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY src/flask/ ./

# Expose the Flask port
EXPOSE ${FLASK_PORT}

# Run the Flask application
CMD ["python", "index.py"]
